### ISSUE TITLE
If you're not going to update this

### ISSUE THREAD

**Issue by Lemorz56** [evanwon/WPFCustomMessageBox#18]
Maybe you can merge updates by other people?
[For Example](https://github.com/NateShoffner/WPFCustomMessageBox)

**Comment by evanwon** [comment]
@Lemorz56 Howdy Sebastian, if you're interested in helping out update the library and merge in changes, I'd welcome the help. Just let me know and I can grant you permissions.

**Comment by kcl93** [comment]
Hi @Lemorz56 
did you get reviewer permissions from @evanwon? I have also opened a PR but given that a previous one from 2013 is still open I fear that nobody will look at the new one...

**Comment by evanwon** [comment]
Hey @kcl93, still looking for a maintainer to join the project! Looking for someone with solid experience in C#/WPF and ideally some relevant experience in open source (e.g. small libraries, nothing crazy).

**Comment by kcl93** [comment]
Hey @evanwon 
I would gladly try to support you here, though it is of course for you to decide whether I am sufficiently experienced for you. I am coding since ~12 years now and proud owner of a few small Arduino libraries. I am programming C# and WPF itself since around 2-3 years now professionally (though less with focus on GUI elements to be honest).

**Comment by kcl93** [comment]
@evanwon thank you for your trust in me!
