### ISSUE TITLE
Add default MessageBoxResult to the window

### ISSUE THREAD

**Issue by DoruLa** [evanwon/WPFCustomMessageBox#9]
You can add a default MessageBoxResult in the DisplayButtons method. That way, if the user clicks on the close button of the window, the result returned will not be None in case of Yes/No/Cancel message boxes.

**Comment by kcl93** [comment]
Hi @DoruLa 
This is actually the intended behavior and a reason why MessageBoxResult.None is a valid result. Changing this would change the expected behavior compared to the original MessageBox. I would suggest to handle the None case in your code together with whatever value your default behavior should be.
